/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InvestigationRouteImport } from './routes/investigation'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as HostsRouteImport } from './routes/hosts'
import { Route as FullScanRouteImport } from './routes/full-scan'
import { Route as BaselineRouteImport } from './routes/baseline'
import { Route as IndexRouteImport } from './routes/index'

const InvestigationRoute = InvestigationRouteImport.update({
  id: '/investigation',
  path: '/investigation',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsRoute = HostsRouteImport.update({
  id: '/hosts',
  path: '/hosts',
  getParentRoute: () => rootRouteImport,
} as any)
const FullScanRoute = FullScanRouteImport.update({
  id: '/full-scan',
  path: '/full-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const BaselineRoute = BaselineRouteImport.update({
  id: '/baseline',
  path: '/baseline',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/baseline': typeof BaselineRoute
  '/full-scan': typeof FullScanRoute
  '/hosts': typeof HostsRoute
  '/incidents': typeof IncidentsRoute
  '/investigation': typeof InvestigationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/baseline': typeof BaselineRoute
  '/full-scan': typeof FullScanRoute
  '/hosts': typeof HostsRoute
  '/incidents': typeof IncidentsRoute
  '/investigation': typeof InvestigationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/baseline': typeof BaselineRoute
  '/full-scan': typeof FullScanRoute
  '/hosts': typeof HostsRoute
  '/incidents': typeof IncidentsRoute
  '/investigation': typeof InvestigationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/baseline'
    | '/full-scan'
    | '/hosts'
    | '/incidents'
    | '/investigation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/baseline'
    | '/full-scan'
    | '/hosts'
    | '/incidents'
    | '/investigation'
  id:
    | '__root__'
    | '/'
    | '/baseline'
    | '/full-scan'
    | '/hosts'
    | '/incidents'
    | '/investigation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BaselineRoute: typeof BaselineRoute
  FullScanRoute: typeof FullScanRoute
  HostsRoute: typeof HostsRoute
  IncidentsRoute: typeof IncidentsRoute
  InvestigationRoute: typeof InvestigationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/investigation': {
      id: '/investigation'
      path: '/investigation'
      fullPath: '/investigation'
      preLoaderRoute: typeof InvestigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts': {
      id: '/hosts'
      path: '/hosts'
      fullPath: '/hosts'
      preLoaderRoute: typeof HostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/full-scan': {
      id: '/full-scan'
      path: '/full-scan'
      fullPath: '/full-scan'
      preLoaderRoute: typeof FullScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baseline': {
      id: '/baseline'
      path: '/baseline'
      fullPath: '/baseline'
      preLoaderRoute: typeof BaselineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BaselineRoute: BaselineRoute,
  FullScanRoute: FullScanRoute,
  HostsRoute: HostsRoute,
  IncidentsRoute: IncidentsRoute,
  InvestigationRoute: InvestigationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
